name: 🛡️ Validacio de Qualitat (CI)

on:
  push:
    branches: [ staging, setup-linting ]
  pull_request:
    branches: [ staging ]

jobs:
  # TASCA 1: VALIDACIÓ DEL FRONTEND
  frontend_lint:
    name: Frontend (Node/TS)
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Checkout Repositori
        uses: actions/checkout@v4

      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instal·lar Dependències (Arrel)
        run: npm install

      - name: Instal·lar Dependències (Frontend)
        run: npm install
        working-directory: ./frontend/

      - name: Executar Linting (ESLint)
        # El linter d'ESLint (incloent Prettier) revisa errors de codi i estil.
        run: npm run lint
        working-directory: ./frontend/

  # TASCA 2: VALIDACIÓ DEL BACKEND
  backend_lint:
    name: Backend (Python)
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Checkout Repositori
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instal·lar Linters
        # Instalació de les eines de qualitat requerides
        run: pip install flake8 black

      - name: Executar Flake8 (Linting)
        # Flake8 comprova errors de PEP8 i estil
        run: flake8 ./api/

      - name: Executar Black (Comprovar Format)
        run: black ./api/ --check